name: Build Windows Terminal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: win-server

    steps:

    - name: Test
      shell: pwsh
      run: |
        ls
    # - name: Setup
    #   shell: pwsh
    #   run: |
    #     git submodule update --init --recursive

    # - name: Build msixbundle
    #   shell: pwsh
    #   run: |
    #     Import-Module .\tools\OpenConsole.psm1
    #     Set-MsBuildDevEnvironment
    #     Invoke-OpenConsoleBuild


