name: Build Windows Terminal

on:
  workflow_call:
    inputs:
      skip_build:
        description: 'Skip Build'
        required: true
        default: 'false'
        type: boolean
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: win-server

    steps:

    # - name: Setup
    #   shell: pwsh
    #   run: |
    #     git submodule update --init --recursive

    - name: Build msixbundle
      shell: pwsh
      run: |
        if ("${{ inputs.skip_build }}" -eq "false")
        {
          Import-Module .\tools\OpenConsole.psm1;
          Set-MsBuildDevEnvironment;
          Invoke-OpenConsoleBuild
        }


    - name: Archive msix file
      uses: actions/upload-artifact@v4
      with:
        name: TerminalBuild
        path: .\src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_0.0.1.0_x64_Debug_Test\CascadiaPackage_0.0.1.0_x64_Debug.msix

    - name: Get AppxManifest
      shell: pwsh
      run : |
        Import-Module .\tools\OpenConsole.psm1;
        Set-MsBuildDevEnvironment;
        Set-Location -Path src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_0.0.1.0_x64_Debug_Test;
        New-Item ..\loose -Type Directory -Force;
        makeappx unpack /v /o /p .\CascadiaPackage_0.0.1.0_x64_Debug.msix /d ..\loose\;


    - name: Archive AppxManifest
      uses: actions/upload-artifact@v4
      with:
        name: AppManifest
        path: .\src\cascadia\CascadiaPackage\AppPackages\loose\AppxManifest.xml


    - name: Attempt Archive Directory
      uses: actions/upload-artifact@v4
      with:
        name: decompiled
        path: .\src\cascadia\CascadiaPackage\AppPackages\loose\
