name: Build Windows Terminal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Developer Mode
      run: Start-Process powershell -ArgumentList 'Set-ExecutionPolicy RemoteSigned -Scope Process -Force; Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart' -Verb RunAs


    # - name: Setup PowerShell
    #   uses: actions/setup-powershell@v1
    #   with:
    #     pwsh-version: 'latest'

    # - name: Make work
    #   shell: pwsh
    #   run: |
    #         winget upgrade --accept-source-agreements --accept-package-agreements --id Microsoft.PowerShell

    - name: Make work
      shell: pwsh
      run: |
        Install-Module -Name Microsoft.WinGet.Client -Force -Confirm:$false
        Import-Module -Name Microsoft.WinGet.Client
        winget configure  --accept-configuration-agreements  --disable-interactivity -f .config\configuration.winget


    - name: Build with PowerShell
      shell: pwsh
      run: |
        Import-Module .\tools\OpenConsole.psm1
        Set-MsBuildDevEnvironment
        Invoke-OpenConsoleBuild
