name: Build Windows Terminal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: win-server

    steps:

    # - name: Setup
    #   shell: pwsh
    #   run: |
    #     git submodule update --init --recursive

    - name: Build msixbundle
      shell: pwsh
      run: |
        Import-Module .\tools\OpenConsole.psm1
        Set-MsBuildDevEnvironment
        Invoke-OpenConsoleBuild


    - name: Archive msix file
      uses: actions/upload-artifact@v4
      with:
        name: TerminalBuild
        path: .\src\cascadia\CascadiaPackage\AppPackages\CascadiaPackage_0.0.1.0_x64_Debug_Test\CascadiaPackage_0.0.1.0_x64_Debug.msix
