name: Build Windows Terminal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Developer Mode
      run: Start-Process powershell -ArgumentList 'Set-ExecutionPolicy RemoteSigned -Scope Process -Force; Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart' -Verb RunAs

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install PowerShell 7
      uses: actions/setup-powershell@v2
      with:
        version: '7.x'

    - name: Install Windows 11 SDK
      run: choco install windows-sdk-11-version-22621-0

    - name: Install Visual Studio 2022
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '2022'

    - name: Install VS Workloads and Components
      run: |
        choco install visualstudio2022-workload-nativedesktop
        choco install visualstudio2022-workload-universal
        choco install visualstudio2022-component-vc143

    - name: Install .NET Framework Targeting Pack
      run: choco install netfx-4.8-devpack

    - name: Build with PowerShell
      shell: pwsh
      run: |
        Import-Module .\tools\OpenConsole.psm1
        Set-MsBuildDevEnvironment
        Invoke-OpenConsoleBuild
